#! /bin/bash

# wrapper script to facilitate CRIU checkpointing on an HPC cluster

export CHECKPOINTER_LIBDIR=/app/lib/checkpointer
source ${CHECKPOINTER_LIBDIR}/checkpointer-lib

if [[ -f ${CHECKPOINTER_LIBDIR}/checkpointer-vars ]]; then
  source ${CHECKPOINTER_LIBDIR}/checkpointer-vars
else
  bootstrap_vars
fi

checkToolDependencies
validateCheckPointerRoot
export CHECKPOINTER_DIR=$(getCheckPointerDir)
if ! [[ -d $CHECKPOINTER_DIR ]]; then
  echoErr "Folder ${CHECKPOINTER_DIR} does not exist"
  exit 1
fi

# more detailed check, currently disabled
#checkEnvironment

#### select the checkpointing tool 
if [[ -n ${SLURM_JOB_ID} ]]; then
  if [[ -n ${SLURM_RESTART_COUNT} ]]; then
    # requeued process 
    ${CHECKPOINTER_LIBDIR}/checkpointer-slurm $@ 
  else
    # first start, spawn a monitoring process
    #echoErr "spawning checkpointer-slurm .. "
    ${CHECKPOINTER_LIBDIR}/checkpointer-slurm $@ & 
  fi
else
  ${CHECKPOINTER_LIBDIR}/checkpointer-generic $@ &
fi

exit

